import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home () {

  const router = useRouter();

  const handleClick = () => {
    console.log("place your order here")
    router.push('/products')
  }

  return (
    <>
    {/* title */}
      <Head>
        <title>Shiro Store | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
        <div>
          <h2 className={styles.title}>Home</h2>
          <p className={styles.text}>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti incidunt, voluptate et sapiente aspernatur nisi similique voluptatem labore harum quis a ipsa, ut vel quas cupiditate consequatur sed itaque tenetur!</p>
          <p className={styles.text}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae voluptate saepe facilis laboriosam consequatur omnis exercitationem rerum culpa assumenda, qui sequi. Earum illum ipsa voluptas atque assumenda laboriosam magni eaque?</p>
          <div className="flex">
            <Link href="/users" className={styles.btn}>see all of users</Link>
            <Link href="/steaks" className={styles.btn}>see all of steaks</Link>
            <button onClick={handleClick} className={styles.btn}>see all of products</button>
          </div>
        </div>
    </>
  );
}
